### ISSUE TITLE
AMD General availability support

### ISSUE THREAD

**Issue by alindima** [firecracker-microvm/firecracker-microvm.github.io#14]
As of Fircracker v0.23, AMD CPU support is now in GA (no longer developer preview).
The website needs to be updated, to be in line with the current supported platforms: https://github.com/firecracker-microvm/firecracker#supported-platforms

**Comment by alindima** [comment]
Also ARM now

**Comment by raduiliescu** [comment]
I don't see what is the issue. We have all docs updated.

**Comment by alindima** [comment]
@raduiliescu I'm referring to the Firecracker website: https://firecracker-microvm.github.io/

**Comment by raduiliescu** [comment]
Reopening since I forgot to update one reference to the developer preview.
